---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# zoter: Zotero API in R

<!-- badges: start -->

<!-- badges: end -->

The goal of {zoter} is to conveniently access the Zotero API v3 from R.

## Installation

You can install the development version of **{zoter}** like so:

``` r
# install.packages("devtools")
devtools::install_github("kleinlennart/zoter")
```

## Usage

### Authentication

To access your own private library you will need your **userID** (not your username!) and an **API Key**.\
You can find them here: [https://www.zotero.org/settings/keys](https://www.zotero.org/settings/keys/new)

```{r auth, eval=FALSE}
library(zoter)

## Will ask you for your userID and API Key
set_zotero_creds()

## Alternatively you can also set them directly with:
Sys.setenv("ZOTERO_API_USER" = "XXXXX")
Sys.setenv("ZOTERO_API_KEY" = "XXXXX")
```

### Example API Calls

```{r example, eval=FALSE}
## Download and parse infos for all top-level items in your library
items <- get_all_items_top()

## Download and parse infos for all collections in your library
colls <- get_all_collections()


## Use 'req_zotero' for more specific queries
trash_keys <- req_zotero(query = "items/trash", output = "raw", format = "keys")
```

### Cleaning

```{r cleaning, eval=FALSE}
```

### Analysis

```{r analysis, eval=FALSE}
# Plots
```
